import React, { useEffect, useMemo, useState } from "react";
import "./production.css";
import "./production-overrides.css";

const jsonRequest = async (url, options = {}) => {
  const response = await fetch(url, { ...options, headers: { "Content-Type": "application/json", ...(options.headers || {}) } });
  const payload = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(payload.message || "The production request could not be completed.");
  return payload;
};

const statusLabel = (value) => String(value || "").replaceAll("_", " ");

export function ProductionSystem({ mode = "runs", onApplicationRefresh }) {
  const [data, setData] = useState({ availableFfb: 0, lines: [], stations: [], machines: [], routings: [], runs: [], inventory: [] });
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [modal, setModal] = useState(null);
  const [selectedRunId, setSelectedRunId] = useState(null);
  const [selectedRoutingId, setSelectedRoutingId] = useState(null);
  const load = async () => { setLoading(true); try { setData(await jsonRequest("/api/production/overview")); setError(""); } catch (err) { setError(err.message); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const selectedRun = useMemo(() => data.runs.find((run) => run.id === selectedRunId), [data.runs, selectedRunId]);
  const selectedRouting = useMemo(() => data.routings.find((routing) => routing.id === selectedRoutingId) || data.routings[0], [data.routings, selectedRoutingId]);
  const activeRuns = data.runs.filter((run) => run.status !== "COMPLETED" && run.status !== "CANCELLED").length;
  const cpoBalance = data.inventory.find((item) => item.material === "CPO")?.balance || 0;
  const availableCapacity = data.lines.reduce((sum, line) => sum + Number(line.available_capacity || 0), 0);
  const isLineMaster = mode === "lineMaster";
  const isMachineMaster = mode === "machineMaster";
  const isStationMaster = mode === "stationMaster";
  const isProductionMaster = mode === "config" || isLineMaster || isMachineMaster;
  const submit = async (event, url, close = true) => {
    event.preventDefault(); setError(""); const form = new FormData(event.currentTarget); const body = Object.fromEntries(form.entries());
    try { await jsonRequest(url, { method: "POST", body: JSON.stringify(body) }); if (close) setModal(null); await load(); if (modal?.type === "completeRun") await onApplicationRefresh?.(); }
    catch (err) { setError(err.message); }
  };
  if (loading) return <div className="production-loading">Loading production routing and capacity…</div>;
  return <main className="production-page">
    <div className="production-breadcrumb"><span>{isProductionMaster || isStationMaster ? "Masters" : "Production"}</span><b>›</b><strong>{mode === "routing" ? "Routing" : isLineMaster ? "Production Line Master" : isMachineMaster ? "Machine Master" : isStationMaster ? "Station Master" : mode === "config" ? "Production Masters" : "Production Runs"}</strong></div>
    {error && <div className="production-error">{error}<button onClick={() => setError("")}>×</button></div>}
    {mode === "runs" && <>
      <div className="production-heading"><div><h1>Production Runs</h1><p>Plan, start and execute FFB manufacturing according to an approved routing.</p></div><button className="btn btn-primary" onClick={() => setModal({ type: "startRun" })}>＋ Start Production Run</button></div>
      <section className="production-kpis"><article><span>Available Received FFB</span><strong>{Number(data.availableFfb).toFixed(3)} MT</strong><small>Eligible inbound quantity</small></article><article><span>Available Mill Capacity</span><strong>{availableCapacity.toFixed(3)} MT</strong><small>Across active lines</small></article><article><span>Active Runs</span><strong>{activeRuns}</strong><small>Planned or in progress</small></article><article><span>CPO Inventory</span><strong>{Number(cpoBalance).toFixed(3)} MT</strong><small>CPO Tank 01</small></article></section>
      <section className="production-readiness"><h2>Production readiness</h2><div><span className={data.availableFfb > 0 ? "ready" : "blocked"}>{data.availableFfb > 0 ? "✓" : "!"} FFB inventory</span><span className={availableCapacity > 0 ? "ready" : "blocked"}>{availableCapacity > 0 ? "✓" : "!"} Mill capacity</span><span className={data.routings.some((item) => item.status === "ACTIVE") ? "ready" : "blocked"}>✓ Active routing</span><span className={data.lines.some((item) => item.status === "ACTIVE") ? "ready" : "blocked"}>✓ Production line</span></div></section>
      <section className="panel production-panel"><div className="production-panel-head"><h2>Production run register</h2><span>{data.runs.length} runs</span></div><div className="table-wrap"><table><thead><tr><th>Run Number</th><th>Routing</th><th>Line</th><th>Planned FFB</th><th>Current Stage</th><th>CPO Output</th><th>Status</th><th>Action</th></tr></thead><tbody>{data.runs.map((run) => <tr key={run.id}><td className="production-reference">{run.run_no}</td><td>{run.routing?.name}</td><td>{run.line?.name}</td><td>{Number(run.planned_ffb_qty).toFixed(3)} MT</td><td>{run.stages.find((stage) => stage.sequence === run.current_step_sequence)?.stage_name || "Complete"}</td><td>{Number(run.cpo_output || 0).toFixed(3)} MT</td><td><span className={`production-status ${run.status.toLowerCase()}`}>{statusLabel(run.status)}</span></td><td><button className="production-link" onClick={() => setSelectedRunId(run.id)}>Open execution</button></td></tr>)}{!data.runs.length && <tr><td colSpan="8" className="production-empty">No production runs have been created.</td></tr>}</tbody></table></div></section>
    </>}
    {mode === "routing" && <>
      <div className="production-heading"><div><h1>Production Routing</h1><p>Define and review the manufacturing sequence from received FFB to CPO and Palm Kernel.</p></div><button className="btn btn-primary" onClick={() => setModal({ type: "routing" })}>＋ New Routing</button></div>
      <div className="routing-layout"><aside className="routing-list">{data.routings.map((routing) => <button className={selectedRouting?.id === routing.id ? "active" : ""} key={routing.id} onClick={() => setSelectedRoutingId(routing.id)}><strong>{routing.name}</strong><span>{routing.code} · Version {routing.version}</span><small>{routing.steps.length} stages · {routing.status}</small></button>)}</aside>{selectedRouting && <section className="routing-view"><div className="routing-title"><div><span>ACTIVE ROUTING</span><h2>{selectedRouting.name}</h2><p>{selectedRouting.code} · Version {selectedRouting.version} · Input {selectedRouting.input_material}</p></div><div>{selectedRouting.outputs.map((output) => <b key={output}>{output}</b>)}</div></div><div className="route-sequence">{selectedRouting.steps.map((step, index) => <article key={step.id}><div className="route-number">{step.sequence}</div><div className="route-card"><div><span>{step.code}</span><h3>{step.name}</h3><p>{step.station}{step.machine ? ` · ${step.machine}` : ""}</p></div><div className="route-meta"><small>{step.input_material || "—"} → {step.output_material || "—"}</small><small>{step.planned_duration_minutes} min</small>{Boolean(step.quality_required) && <b>Quality every {step.quality_frequency_minutes || "configured"} min</b>}</div></div>{index < selectedRouting.steps.length - 1 && <div className="route-arrow">↓</div>}</article>)}</div></section>}</div>
    </>}
    {isStationMaster && <>
      <div className="production-heading"><div><h1>Station Master</h1><p>Maintain the physical and functional sections of the palm oil mill used by machines, routings and quality checkpoints.</p></div><button className="btn btn-primary" onClick={() => setModal({ type: "station" })}>＋ Add Station</button></div>
      <section className="panel production-panel"><div className="production-panel-head"><h2>Mill Stations</h2><span>{data.stations.length} stations</span></div><div className="table-wrap"><table><thead><tr><th>Sequence</th><th>Station Code</th><th>Station Name</th><th>Mill</th><th>Section Type</th><th>Description</th><th>Status</th></tr></thead><tbody>{data.stations.map((station) => <tr key={station.id}><td>{station.sequence}</td><td className="production-reference">{station.code}</td><td>{station.name}</td><td>{station.mill}</td><td>{station.section_type}</td><td>{station.description || "—"}</td><td><span className="production-status completed">{station.status}</span></td></tr>)}</tbody></table></div></section>
    </>}
    {isProductionMaster && <>
      <div className="production-heading"><div><h1>{isLineMaster ? "Production Line Master" : isMachineMaster ? "Machine Master" : "Production Masters"}</h1><p>{isLineMaster ? "Maintain mill production lines, shifts and available manufacturing capacity." : isMachineMaster ? "Maintain machines, process stations, line assignments and rated capacities." : "Maintain mill lines, machines and the capacity masters required before production starts."}</p></div><div className="production-heading-actions">{!isLineMaster && <button className="btn btn-secondary" onClick={() => setModal({ type: "machine" })}>＋ Machine</button>}{!isMachineMaster && <button className="btn btn-primary" onClick={() => setModal({ type: "line" })}>＋ Production Line</button>}</div></div>
      <section className={`config-grid ${isLineMaster || isMachineMaster ? "single" : ""}`}>{!isMachineMaster && <article className="panel"><div className="production-panel-head"><h2>Production Lines</h2><span>{data.lines.length}</span></div>{data.lines.map((line) => <div className="config-row" key={line.id}><div><strong>{line.name}</strong><span>{line.code} · {line.shift_hours} hour shift</span></div><div><strong>{Number(line.capacity_per_shift).toFixed(3)} {line.capacity_uom}</strong><span>{Number(line.available_capacity).toFixed(3)} available</span></div></div>)}</article>}{!isLineMaster && <article className="panel"><div className="production-panel-head"><h2>Machines & Stations</h2><span>{data.machines.length}</span></div>{data.machines.map((machine) => <div className="config-row" key={machine.id}><div><strong>{machine.name}</strong><span>{machine.code} · {machine.station}</span></div><div><strong>{machine.rated_capacity || "—"}</strong><span>{machine.capacity_uom}</span></div></div>)}</article>}</section>
      {mode === "config" && <section className="panel production-master-map"><div className="production-panel-head"><h2>Required manufacturing masters</h2><span>Core architecture</span></div><div>{["Materials & UOM","Production lines","Machines & stations","Routing versions","Routing stages","Quality parameters","Sampling frequency","Storage locations","Shift calendar","Loss reasons"].map((item) => <span key={item}>✓ {item}</span>)}</div></section>}
    </>}
    {selectedRun && <RunExecution run={selectedRun} onClose={() => setSelectedRunId(null)} onAction={setModal} />}
    {modal && <ProductionModal modal={modal} data={data} error={error} onClose={() => { setModal(null); setError(""); }} onSubmit={submit} reload={load} setError={setError} />}
  </main>;
}

function RunExecution({ run, onClose, onAction }) {
  const completed = run.stages.filter((stage) => stage.status === "COMPLETED").length;
  return <div className="production-execution"><div className="execution-head"><div><span>PRODUCTION EXECUTION</span><h2>{run.run_no}</h2><p>{run.routing?.name} · {run.line?.name} · {Number(run.planned_ffb_qty).toFixed(3)} MT FFB</p></div><button onClick={onClose}>×</button></div><div className="execution-progress"><div><span>Routing progress</span><strong>{completed} / {run.stages.length} stages</strong></div><i><b style={{ width: `${run.stages.length ? completed / run.stages.length * 100 : 0}%` }} /></i></div><div className="execution-stages">{run.stages.map((stage) => <article key={stage.id} className={stage.status.toLowerCase()}><div className="execution-sequence">{stage.sequence}</div><div className="execution-stage-main"><div><span>{stage.station}</span><h3>{stage.stage_name}</h3><p>{stage.machine || "No machine assigned"}</p></div><div className="execution-quantities"><span>Input <b>{stage.input_qty ?? "—"}</b></span><span>Output <b>{stage.output_qty ?? "—"}</b></span><span>Loss <b>{stage.loss_qty ?? "—"}</b></span></div><div className="execution-quality"><span>{stage.quality_required ? `Quality: ${stage.quality_frequency_minutes || "configured"} min` : "Quality: as required"}</span><b>{stage.qualityResults.length} results</b></div></div><div className="execution-actions"><span className={`production-status ${stage.status.toLowerCase()}`}>{statusLabel(stage.status)}</span><button disabled={stage.status !== "PENDING"} onClick={() => onAction({ type: "startStage", run, stage })}>Start</button><button disabled={stage.status !== "IN_PROGRESS"} onClick={() => onAction({ type: "completeStage", run, stage })}>Record output</button><button disabled={stage.status === "PENDING"} onClick={() => onAction({ type: "quality", run, stage })}>Quality test</button></div></article>)}</div><div className="execution-footer"><div><span>Total recorded loss</span><strong>{Number(run.total_loss || 0).toFixed(3)} MT</strong></div><button className="btn btn-primary" disabled={completed !== run.stages.length || run.status === "COMPLETED"} onClick={() => onAction({ type: "completeRun", run })}>{run.status === "COMPLETED" ? "Production Completed" : "Complete Production Run"}</button></div></div>;
}

function ProductionModal({ modal, data, error, onClose, onSubmit, reload, setError }) {
  const [steps, setSteps] = useState([{ name: "", code: "STEP-01", station: "", machine: "", inputMaterial: "FFB", outputMaterial: "", durationMinutes: 60, qualityRequired: true, qualityFrequencyMinutes: 120 }]);
  const act = async (url) => { setError(""); try { await jsonRequest(url, { method: "POST", body: "{}" }); onClose(); await reload(); } catch (err) { setError(err.message); } };
  const routingSubmit = async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); try { await jsonRequest('/api/production/routings', { method: 'POST', body: JSON.stringify({ code: form.get('code'), name: form.get('name'), version: form.get('version'), inputMaterial: 'FFB', outputs: ['CPO','PK'], steps }) }); onClose(); await reload(); } catch (err) { setError(err.message); } };
  const updateStep = (index, key, value) => setSteps((current) => current.map((step, stepIndex) => stepIndex === index ? { ...step, [key]: value } : step));
  return <div className="production-modal-backdrop"><form className="production-modal" onSubmit={modal.type === "routing" ? routingSubmit : modal.type === "startRun" ? (event) => onSubmit(event, "/api/production/runs") : modal.type === "line" ? (event) => onSubmit(event, "/api/production/lines") : modal.type === "machine" ? (event) => onSubmit(event, "/api/production/machines") : modal.type === "station" ? (event) => onSubmit(event, "/api/production/stations") : modal.type === "completeStage" ? (event) => onSubmit(event, `/api/production/runs/${modal.run.id}/stages/${modal.stage.id}/complete`) : modal.type === "quality" ? (event) => onSubmit(event, `/api/production/runs/${modal.run.id}/stages/${modal.stage.id}/quality`) : modal.type === "completeRun" ? (event) => onSubmit(event, `/api/production/runs/${modal.run.id}/complete`) : (event) => { event.preventDefault(); act(`/api/production/runs/${modal.run.id}/stages/${modal.stage.id}/start`); }}><div className="production-modal-head"><div><span>PRODUCTION / MANUFACTURING</span><h2>{({ startRun:"Start Production Run", routing:"Create Production Routing", line:"Add Production Line", machine:"Add Machine", station:"Add Mill Station", startStage:"Start Routing Stage", completeStage:"Record Stage Quantities", quality:"Capture Periodic Quality Test", completeRun:"Complete Production Run" })[modal.type]}</h2></div><button type="button" onClick={onClose}>×</button></div>{error && <div className="production-error">{error}</div>}
    {modal.type === "startRun" && <div className="production-form-grid"><label>Available FFB<input disabled value={`${Number(data.availableFfb).toFixed(3)} MT`} /></label><label>Routing<select name="routingId" required><option value="">Select active routing…</option>{data.routings.filter((item) => item.status === "ACTIVE").map((item) => <option key={item.id} value={item.id}>{item.code} · {item.name}</option>)}</select></label><label>Production Line<select name="lineId" required><option value="">Select line…</option>{data.lines.filter((item) => item.status === "ACTIVE").map((item) => <option key={item.id} value={item.id}>{item.name} · {Number(item.available_capacity).toFixed(3)} MT available</option>)}</select></label><label>Planned FFB Quantity (MT)<input name="plannedFfbQty" type="number" min="0.001" step="0.001" required /></label></div>}
    {modal.type === "line" && <div className="production-form-grid"><label>Line Code<input name="code" required /></label><label>Line Name<input name="name" required /></label><label>Capacity per Shift (MT)<input name="capacityPerShift" type="number" min="0.001" step="0.001" required /></label><label>Shift Hours<input name="shiftHours" type="number" min="1" defaultValue="8" required /></label><input type="hidden" name="capacityUom" value="MT" /></div>}
    {modal.type === "machine" && <div className="production-form-grid"><label>Machine Code<input name="code" required /></label><label>Machine Name<input name="name" required /></label><label>Station<select name="station" required><option value="">Select mill station…</option>{data.stations.map((station) => <option key={station.id} value={station.name}>{station.code} · {station.name}</option>)}</select></label><label>Production Line<select name="lineId"><option value="">Unassigned</option>{data.lines.map((line) => <option key={line.id} value={line.id}>{line.name}</option>)}</select></label><label>Rated Capacity<input name="ratedCapacity" type="number" min="0" step="0.001" /></label><label>Capacity UOM<input name="capacityUom" defaultValue="MT/HOUR" /></label></div>}
    {modal.type === "station" && <div className="production-form-grid"><label>Station Code<input name="code" placeholder="e.g. ST-PRESS" required /></label><label>Station Name<input name="name" placeholder="e.g. Pressing" required /></label><label>Mill<input name="mill" defaultValue="Main Mill" required /></label><label>Section Type<select name="sectionType" required><option value="">Select section type…</option><option>Receiving</option><option>Processing</option><option>Oil Recovery</option><option>Kernel Plant</option><option>Storage</option><option>Utilities</option><option>Quality Laboratory</option><option>Dispatch</option></select></label><label>Routing Sequence<input name="sequence" type="number" min="1" defaultValue="1" required /></label><label className="wide">Description<textarea name="description" rows="3" placeholder="Purpose and operational boundary of this mill station" /></label></div>}
    {modal.type === "routing" && <><div className="production-form-grid"><label>Routing Code<input name="code" required /></label><label>Routing Name<input name="name" required /></label><label>Version<input name="version" type="number" min="1" defaultValue="1" required /></label><label>Outputs<input disabled value="CPO, Palm Kernel" /></label></div><div className="routing-builder"><div className="routing-builder-head"><h3>Routing Stages</h3><button type="button" onClick={() => setSteps((current) => [...current, { name:"", code:`STEP-${String(current.length + 1).padStart(2,"0")}`, station:"", machine:"", inputMaterial:"", outputMaterial:"", durationMinutes:60, qualityRequired:false, qualityFrequencyMinutes:120 }])}>＋ Add Stage</button></div>{steps.map((step, index) => <div className="routing-builder-row" key={index}><b>{index + 1}</b><input value={step.code} onChange={(e) => updateStep(index,"code",e.target.value)} placeholder="Code" required /><input value={step.name} onChange={(e) => updateStep(index,"name",e.target.value)} placeholder="Stage name" required /><input value={step.station} onChange={(e) => updateStep(index,"station",e.target.value)} placeholder="Station" required /><select value={step.machine} onChange={(e) => updateStep(index,"machine",e.target.value)}><option value="">Machine…</option>{data.machines.map((machine) => <option key={machine.id}>{machine.name}</option>)}</select><input value={step.outputMaterial} onChange={(e) => updateStep(index,"outputMaterial",e.target.value)} placeholder="Output material" /><label className="route-quality-check"><input type="checkbox" checked={step.qualityRequired} onChange={(e) => updateStep(index,"qualityRequired",e.target.checked)} /> Quality</label><button type="button" disabled={steps.length === 1} onClick={() => setSteps((current) => current.filter((_, stepIndex) => stepIndex !== index))}>×</button></div>)}</div></>}
    {modal.type === "startStage" && <div className="production-confirm"><strong>{modal.stage.sequence}. {modal.stage.stage_name}</strong><p>Starting this stage records the actual start time and changes the production run to In Progress.</p></div>}
    {modal.type === "completeStage" && <div className="production-form-grid"><label>Input Quantity (MT)<input name="inputQty" type="number" min="0" step="0.001" required /></label><label>Output Quantity (MT)<input name="outputQty" type="number" min="0" step="0.001" required /></label><label>Loss Quantity (MT)<input name="lossQty" type="number" min="0" step="0.001" defaultValue="0" required /></label><label className="wide">Remarks<textarea name="remarks" rows="3" /></label></div>}
    {modal.type === "quality" && <div className="production-form-grid"><label>Process Station<input disabled value={modal.stage.station} /></label><label>Quality Parameter<input name="parameter" placeholder="e.g. FFA, Moisture, Temperature" required /></label><label>Result<input name="resultValue" required /></label><label>UOM<input name="uom" placeholder="%, °C, ppm" /></label><label>Test Status<select name="status" required><option>PASS</option><option>REVIEW</option><option>OUT_OF_SPEC</option></select></label><label>Tested By<input name="testedBy" defaultValue="Sean Shapiro" required /></label><label className="wide">Remarks<textarea name="remarks" rows="3" /></label></div>}
    {modal.type === "completeRun" && <div className="production-form-grid"><label>CPO Output to CPO Tank 01 (MT)<input name="cpoOutput" type="number" min="0.001" step="0.001" required /></label><label>Palm Kernel Output to Kernel Silo (MT)<input name="pkOutput" type="number" min="0" step="0.001" defaultValue="0" required /></label></div>}
    <div className="production-modal-actions"><button type="button" className="btn btn-secondary" onClick={onClose}>Cancel</button><button className="btn btn-primary">{modal.type === "startStage" ? "Start Stage" : modal.type === "quality" ? "Save Quality Result" : modal.type === "completeStage" ? "Complete Stage" : modal.type === "completeRun" ? "Post Production Outputs" : "Save"}</button></div></form></div>;
}
