import React, { useEffect, useState } from "react";
import "./masters.css";
import "./logistics-records.css";

const transporters = [{ id: "TR-MY-001", companyName: "Kencana Haulage Sdn. Bhd." }, { id: "TR-MY-002", companyName: "Southern Palm Logistics Sdn. Bhd." }, { id: "TR-MY-003", companyName: "Perak Bulk Transport Sdn. Bhd." }, { id: "TR-MY-005", companyName: "East Coast Fleet Services Sdn. Bhd." }];
const api = async (url, options = {}) => { const response = await fetch(url, { ...options, headers: { "Content-Type": "application/json", ...(options.headers || {}) } }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.message || "Unable to save driver."); return body; };
const toImage = (file) => file ? new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.onerror = reject; reader.readAsDataURL(file); }) : Promise.resolve("");

function DriverDetails({ driver, onBack, onEdit }) {
  return <main className="masters-page"><div className="masters-breadcrumb"><button className="link-button" onClick={onBack}>Drivers</button><b>›</b><strong>Details</strong></div><div className="masters-heading"><div><span className="eyebrow">LOGISTICS / DRIVERS</span><h1>{driver.name}</h1><p>{driver.license_no} · {driver.transporter}</p></div><div className="detail-header-actions"><button className="btn btn-secondary" onClick={onBack}>Back to Listing</button><button className="btn btn-primary" onClick={onEdit}>Edit Driver</button></div></div><div className="transporter-detail-layout"><section className="transporter-detail-card"><h2>Driver Information</h2>{driver.image_data && <img className="master-record-image" src={driver.image_data} alt={driver.name} />}<div className="transporter-detail-grid"><div><span>Driver Name</span><strong>{driver.name}</strong></div><div><span>License Number</span><strong>{driver.license_no}</strong></div><div><span>Phone</span><strong>{driver.phone || "—"}</strong></div><div><span>Status</span><strong>{driver.status}</strong></div></div></section><section className="transporter-detail-card"><h2>Transporter Mapping</h2><div className="transporter-detail-grid"><div><span>Transporter</span><strong>{driver.transporter}</strong></div><div><span>Identity Type</span><strong>{driver.identity_type || "Driving License"}</strong></div></div></section></div></main>;
}

export function DriversMaster() {
  const [rows, setRows] = useState([]); const [selected, setSelected] = useState(null); const [editing, setEditing] = useState(null); const [showForm, setShowForm] = useState(false); const [error, setError] = useState("");
  const load = () => api("/api/drivers").then((items) => setRows(Array.isArray(items) ? items : [])).catch((err) => setError(err.message));
  useEffect(() => { load(); }, []);
  const submit = async (event) => { event.preventDefault(); setError(""); const form = event.currentTarget; const body = Object.fromEntries(new FormData(form).entries()); body.imageData = await toImage(form.elements.image.files[0]); try { await api(editing ? "/api/drivers/" + editing.id : "/api/drivers", { method: editing ? "PUT" : "POST", body: JSON.stringify(body) }); setShowForm(false); setEditing(null); await load(); } catch (err) { setError(err.message); } };
  if (selected) return <DriverDetails driver={selected} onBack={() => setSelected(null)} onEdit={() => { setEditing(selected); setSelected(null); setShowForm(true); }} />;
  return <main className="masters-page"><div className="masters-breadcrumb"><span>Logistics</span><b>›</b><strong>Drivers</strong></div><div className="masters-heading"><div><h1>Drivers</h1><p>Manage drivers and their transporter assignments.</p></div><button className="btn btn-primary" onClick={() => { setEditing(null); setError(""); setShowForm(true); }}>＋ Add Driver</button></div>{error && <div className="master-error">{error}</div>}<section className="panel masters-panel"><div className="masters-toolbar"><strong>Driver register</strong><span>{rows.length} records</span></div><div className="table-wrap"><table><thead><tr><th>Driver Name</th><th>License Number</th><th>Phone</th><th>Transporter</th><th>Status</th></tr></thead><tbody>{rows.map((driver) => <tr key={driver.id} onClick={() => setSelected(driver)}><td><button className="table-link">{driver.name}</button></td><td>{driver.license_no}</td><td>{driver.phone || "—"}</td><td>{driver.transporter || "—"}</td><td>{driver.status}</td></tr>)}{!rows.length && <tr><td colSpan="5" className="master-empty">No drivers registered.</td></tr>}</tbody></table></div></section>{showForm && <div className="master-modal-backdrop"><form className="master-form" onSubmit={submit}><div className="master-form-head"><div><span>LOGISTICS / DRIVERS</span><h2>{editing ? "Edit Driver" : "Add Driver"}</h2><p>Create or update a driver and transporter mapping.</p></div><button type="button" onClick={() => { setShowForm(false); setEditing(null); }}>×</button></div><div className="master-form-grid"><label>Driver Name<em>*</em><input name="name" defaultValue={editing?.name || ""} required /></label><label>License Number<em>*</em><input name="licenseNo" defaultValue={editing?.license_no || ""} required /></label><label>Phone Number<input name="phone" defaultValue={editing?.phone || ""} /></label><label>Transporter<em>*</em><select name="transporter" defaultValue={editing?.transporter || ""} required><option value="">Select transporter...</option>{transporters.map((item) => <option key={item.id}>{item.companyName}</option>)}</select></label><label>Status<select name="status" defaultValue={editing?.status || "ACTIVE"}><option>ACTIVE</option><option>INACTIVE</option></select></label><label>Driver Image<input name="image" type="file" accept="image/jpeg,image/png" /></label></div>{editing?.image_data && <img className="master-record-image" src={editing.image_data} alt="Current driver" />}<div className="master-form-actions"><button type="button" className="btn btn-secondary" onClick={() => setShowForm(false)}>Cancel</button><button className="btn btn-primary">Save</button></div></form></div>}</main>;
}
