import React, { useMemo, useState } from "react";
import { RichTextEditor } from "../components/RichTextEditor.jsx";

const money = (value, currency) => `${currency} ${Number(value || 0).toLocaleString(undefined, { minimumFractionDigits: 2 })}`;

export function PaymentForm({ onSaved }) {
  const [notes, setNotes] = useState("");
  const [error, setError] = useState("");
  const save = async (event) => {
    event.preventDefault(); setError(""); const form = new FormData(event.currentTarget);
    const response = await fetch("/api/payments", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ paymentType: form.get("paymentType"), party: form.get("party"), paymentDate: form.get("paymentDate"), currency: form.get("currency"), amount: form.get("amount"), paymentMethod: form.get("paymentMethod"), reference: form.get("reference"), notesText: notes }) });
    const payload = await response.json(); if (!response.ok) { setError(payload.message || "Unable to save payment."); return; } onSaved?.(payload);
  };
  return <main className="customer-list-page"><div className="customer-breadcrumb"><span>Finance</span><b>›</b><strong>Payments</strong></div><div className="customer-list-heading"><div><div className="eyebrow">FINANCE</div><h1>New Payment</h1><p>Record a supplier, customer or other approved payment.</p></div></div><form className="panel finance-form" onSubmit={save}>{error && <div className="form-error">{error}</div>}<div className="contract-grid three"><label className="contract-field">Payment type<em>*</em><select name="paymentType" required><option>Supplier payment</option><option>Customer receipt</option><option>Other payment</option></select></label><label className="contract-field">Party<em>*</em><input name="party" required placeholder="Supplier or customer" /></label><label className="contract-field">Payment date<em>*</em><input name="paymentDate" required type="date" /></label><label className="contract-field">Currency<em>*</em><select name="currency" defaultValue="MYR"><option>MYR</option><option>USD</option><option>IDR</option></select></label><label className="contract-field">Amount<em>*</em><input name="amount" required type="number" min="0.01" step="0.01" /></label><label className="contract-field">Payment method<em>*</em><select name="paymentMethod" required><option>Bank transfer</option><option>Cash</option><option>Cheque</option><option>Other</option></select></label><label className="contract-field">Reference<input name="reference" placeholder="Bank or receipt reference" /></label></div><section className="contract-section"><RichTextEditor label="Payment notes & terms" value={notes} onChange={setNotes} /></section><div className="contract-actions"><button type="button" className="btn btn-secondary">Cancel</button><button className="btn btn-primary">Save Payment</button></div></form></main>;
}

function Detail({ payment, onBack }) { return <main className="customer-list-page"><div className="customer-breadcrumb"><button className="link-button" onClick={onBack}>Payments</button><b>›</b><strong>Details</strong></div><div className="customer-list-heading"><div><div className="eyebrow">FINANCE / PAYMENTS</div><h1>{payment.payment_number}</h1><p>Payment transaction details</p></div><button className="btn btn-secondary" onClick={onBack}>Back to Listing</button></div><article className="panel invoice-detail-card"><div className="invoice-status-row"><span className="customer-status">{payment.status}</span><strong>{money(payment.amount, payment.currency)}</strong></div><div className="invoice-detail-grid"><div><span>Payment type</span><strong>{payment.payment_type}</strong></div><div><span>Party</span><strong>{payment.party}</strong></div><div><span>Payment date</span><strong>{payment.payment_date}</strong></div><div><span>Payment method</span><strong>{payment.payment_method}</strong></div><div><span>Reference</span><strong>{payment.reference || "—"}</strong></div></div><h2>Notes & Terms</h2><div className="contract-terms-copy" dangerouslySetInnerHTML={{ __html: payment.notes_text || "No payment notes recorded." }} /></article></main>; }

export function PaymentsPage({ rows, onRefresh, onNew }) {
  const [search, setSearch] = useState(""); const [selected, setSelected] = useState(null);
  const filtered = useMemo(() => rows.filter((row) => `${row.payment_number} ${row.payment_type} ${row.party} ${row.status}`.toLowerCase().includes(search.toLowerCase())), [rows, search]);
  const open = async (row) => { const response = await fetch(`/api/payments/${row.id}`); if (response.ok) setSelected(await response.json()); };
  if (selected) return <Detail payment={selected} onBack={() => setSelected(null)} />;
  return <main className="customer-list-page"><div className="customer-breadcrumb"><span>Finance</span><b>›</b><strong>Payments</strong></div><div className="customer-list-heading"><div><div className="eyebrow">FINANCE</div><h1>Payments</h1><p>Supplier payments, customer receipts and payment status.</p></div><div className="heading-actions"><button className="btn btn-secondary" onClick={onRefresh}>Refresh</button><button className="btn btn-primary" onClick={onNew}>+ Add New Payment</button></div></div><article className="panel customer-list-panel"><div className="items-toolbar"><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search payment, party or status..." /><span>{filtered.length} payments</span></div><div className="table-wrap"><table className="customer-table"><thead><tr><th>Payment number</th><th>Type</th><th>Party</th><th>Date</th><th>Amount</th><th>Status</th></tr></thead><tbody>{filtered.map((row) => <tr key={row.id} className="clickable-table-row" onClick={() => open(row)}><td><button className="table-link">{row.payment_number}</button></td><td>{row.payment_type}</td><td>{row.party}</td><td>{row.payment_date}</td><td>{money(row.amount, row.currency)}</td><td><span className="customer-status">{row.status}</span></td></tr>)}{!filtered.length && <tr><td colSpan="6" className="items-empty">No payments found.</td></tr>}</tbody></table></div></article></main>;
}
