export function registerSalesInvoicesModule(app, db) {
  db.exec(`CREATE TABLE IF NOT EXISTS sales_invoices (
    id INTEGER PRIMARY KEY AUTOINCREMENT, tenant_id TEXT NOT NULL, mill_id TEXT NOT NULL,
    invoice_number TEXT NOT NULL, customer TEXT NOT NULL, invoice_date TEXT NOT NULL,
    due_date TEXT, reference TEXT, currency TEXT NOT NULL, subtotal REAL NOT NULL,
    tax_amount REAL NOT NULL DEFAULT 0, total_amount REAL NOT NULL, status TEXT NOT NULL DEFAULT 'DRAFT'
      CHECK(status IN ('DRAFT','UNPAID','PAID')), terms_text TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL,
    UNIQUE(tenant_id, mill_id, invoice_number)
  );
  CREATE TABLE IF NOT EXISTS sales_invoice_lines (
    id INTEGER PRIMARY KEY AUTOINCREMENT, invoice_id INTEGER NOT NULL REFERENCES sales_invoices(id),
    description TEXT NOT NULL, quantity REAL NOT NULL CHECK(quantity > 0), unit_price REAL NOT NULL CHECK(unit_price >= 0), line_total REAL NOT NULL
  );`);
  const context = (req) => ({ tenantId: req.get('X-Tenant-Id') || 'demo-tenant', millId: req.get('X-Mill-Id') || 'demo-mill' });
  const query = `SELECT * FROM sales_invoices WHERE tenant_id=? AND mill_id=?`;
  app.get('/api/sales-invoices', (req, res) => { const { tenantId, millId } = context(req); res.json(db.prepare(`${query} ORDER BY id DESC`).all(tenantId, millId)); });
  app.get('/api/sales-invoices/:id', (req, res) => { const { tenantId, millId } = context(req); const invoice = db.prepare(`${query} AND id=?`).get(tenantId, millId, req.params.id); if (!invoice) return res.status(404).json({ message: 'Sales invoice not found.' }); const lines = db.prepare('SELECT * FROM sales_invoice_lines WHERE invoice_id=? ORDER BY id').all(invoice.id); res.json({ ...invoice, lines }); });
  app.post('/api/sales-invoices', (req, res) => { const { tenantId, millId } = context(req); const body = req.body || {}; const lines = Array.isArray(body.lines) ? body.lines : []; if (!body.customer || !body.invoiceDate || !body.currency || !lines.length) return res.status(400).json({ message: 'Customer, invoice date, currency and at least one line are required.' }); const normalized = lines.map((line) => ({ description: String(line.description || '').trim(), quantity: Number(line.quantity), unitPrice: Number(line.unitPrice) })); if (normalized.some((line) => !line.description || !Number.isFinite(line.quantity) || line.quantity <= 0 || !Number.isFinite(line.unitPrice) || line.unitPrice < 0)) return res.status(400).json({ message: 'Each invoice line requires a description, positive quantity and non-negative unit price.' }); try { const created = db.transaction(() => { const count = db.prepare('SELECT COUNT(*) AS count FROM sales_invoices WHERE tenant_id=? AND mill_id=?').get(tenantId, millId).count + 1; const number = body.invoiceNumber?.trim() || `SI-${new Date().toISOString().slice(0,10).replaceAll('-', '')}-${String(count).padStart(4, '0')}`; const subtotal = Number(normalized.reduce((sum, line) => sum + line.quantity * line.unitPrice, 0).toFixed(2)); const taxAmount = Number((subtotal * (Number(body.taxRate || 0) / 100)).toFixed(2)); const total = Number((subtotal + taxAmount).toFixed(2)); const info = db.prepare('INSERT INTO sales_invoices (tenant_id,mill_id,invoice_number,customer,invoice_date,due_date,reference,currency,subtotal,tax_amount,total_amount,status,terms_text,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,\'DRAFT\',?,?)').run(tenantId, millId, number, body.customer, body.invoiceDate, body.dueDate || '', body.reference || '', body.currency, subtotal, taxAmount, total, body.termsText || '', new Date().toISOString()); const insert = db.prepare('INSERT INTO sales_invoice_lines (invoice_id,description,quantity,unit_price,line_total) VALUES (?,?,?,?,?)'); normalized.forEach((line) => insert.run(info.lastInsertRowid, line.description, line.quantity, line.unitPrice, Number((line.quantity * line.unitPrice).toFixed(2)))); return db.prepare(`${query} AND id=?`).get(tenantId, millId, info.lastInsertRowid); })(); res.status(201).json({ ...created, lines: db.prepare('SELECT * FROM sales_invoice_lines WHERE invoice_id=?').all(created.id) }); } catch (error) { res.status(409).json({ message: error.code === 'SQLITE_CONSTRAINT_UNIQUE' ? 'Invoice number must be unique.' : 'Unable to save sales invoice.' }); } });
}
