export const masterDefinitions = [
  { key: 'uoms', title: 'Units of Measure', category: 'Material foundation', description: 'Controlled quantity units and precision.', permission: 'configuration.manage', fields: [
    { key: 'code', label: 'Code', required: true }, { key: 'name', label: 'Name', required: true }, { key: 'symbol', label: 'Symbol', required: true }, { key: 'category', label: 'Category', type: 'select', options: ['Mass', 'Volume', 'Percentage', 'Count'], required: true }, { key: 'precision', label: 'Decimal precision', type: 'number', required: true }, { key: 'active', label: 'Active', type: 'checkbox' }
  ], seed: [{ id: 'UOM-001', code: 'T', name: 'Tonne', symbol: 't', category: 'Mass', precision: 3, active: true }, { id: 'UOM-002', code: 'KG', name: 'Kilogram', symbol: 'kg', category: 'Mass', precision: 0, active: true }], columns: ['code', 'name', 'symbol', 'category', 'precision', 'active'] },
  { key: 'materials', title: 'Materials', category: 'Material foundation', description: 'Stock-tracked raw materials, products and by-products.', permission: 'configuration.manage', fields: [
    { key: 'code', label: 'Code', required: true }, { key: 'name', label: 'Name', required: true }, { key: 'category', label: 'Category', type: 'select', options: ['Raw Material', 'Intermediate', 'Finished Product', 'By-product', 'Waste/Residue'], required: true }, { key: 'baseUom', label: 'Base UOM', required: true }, { key: 'stockTracked', label: 'Stock tracked', type: 'checkbox' }, { key: 'qualityControlled', label: 'Quality controlled', type: 'checkbox' }, { key: 'dispatchable', label: 'Dispatchable', type: 'checkbox' }, { key: 'active', label: 'Active', type: 'checkbox' }
  ], seed: [{ id: 'MAT-001', code: 'FFB', name: 'Fresh Fruit Bunches', category: 'Raw Material', baseUom: 't', stockTracked: true, qualityControlled: true, dispatchable: false, active: true }, { id: 'MAT-002', code: 'CPO', name: 'Crude Palm Oil', category: 'Finished Product', baseUom: 't', stockTracked: true, qualityControlled: true, dispatchable: true, active: true }, { id: 'MAT-003', code: 'PK', name: 'Palm Kernel', category: 'Finished Product', baseUom: 't', stockTracked: true, qualityControlled: true, dispatchable: true, active: true }, { id: 'MAT-004', code: 'EFB', name: 'Empty Fruit Bunches', category: 'By-product', baseUom: 't', stockTracked: true, qualityControlled: false, dispatchable: false, active: true }], columns: ['code', 'name', 'category', 'baseUom', 'active'] },
  { key: 'customers', title: 'Customers', category: 'Commercial', description: 'Commercial counterparties for future sales contracts.', permission: 'customer.manage', fields: [
    { key: 'code', label: 'Code', required: true }, { key: 'name', label: 'Name', required: true }, { key: 'contact', label: 'Primary contact' }, { key: 'email', label: 'Email', type: 'email' }, { key: 'active', label: 'Active', type: 'checkbox' }
  ], seed: [{ id: 'CUS-001', code: 'GOLDEN-OILS', name: 'Golden Oils Sdn Bhd', contact: 'Commercial Desk', email: 'commercial@goldenoils.example', active: true }], columns: ['code', 'name', 'contact', 'email', 'active'] },
  { key: 'suppliers', title: 'Suppliers', category: 'Commercial', description: 'Estate and dealer sources for future procurement.', permission: 'supplier.manage', fields: [
    { key: 'code', label: 'Code', required: true }, { key: 'name', label: 'Name', required: true }, { key: 'supplierType', label: 'Supplier type', type: 'select', options: ['Estate', 'Dealer'], required: true }, { key: 'contact', label: 'Primary contact' }, { key: 'phone', label: 'Phone' }, { key: 'active', label: 'Active', type: 'checkbox' }
  ], seed: [{ id: 'SUP-001', code: 'KAMPUNG', name: 'Kampung Estate', supplierType: 'Estate', contact: 'Estate Office', phone: '+60 00 000 0000', active: true }, { id: 'SUP-002', code: 'SINAR-JAYA', name: 'Sinar Jaya Trading', supplierType: 'Dealer', contact: 'Receiving Desk', phone: '+60 00 000 0001', active: true }], columns: ['code', 'name', 'supplierType', 'contact', 'active'] },
  { key: 'deliveryTerms', title: 'Delivery Terms', category: 'Commercial', description: 'Controlled delivery and handover terms used by supplier supply items.', permission: 'master.manage', fields: [
    { key: 'code', label: 'Code', required: true }, { key: 'name', label: 'Delivery Term', required: true }, { key: 'description', label: 'Description' }, { key: 'active', label: 'Active', type: 'checkbox' }
  ], seed: [{ id: 'TERM-001', code: 'DAP-MILL', name: 'Delivered to Mill (DAP)', description: 'Supplier delivers material to the mill weighbridge.', active: true }, { id: 'TERM-002', code: 'EXW-ESTATE', name: 'Ex-Estate / Farmgate (EXW)', description: 'Buyer collects material from the supplier location.', active: true }, { id: 'TERM-003', code: 'FOB-PORT', name: 'FOB Port Terminal', description: 'Delivery responsibility ends at the nominated port terminal.', active: true }, { id: 'TERM-004', code: 'CIF-PORT', name: 'CIF Port', description: 'Supplier covers cost, insurance and freight to the port.', active: true }], columns: ['code', 'name', 'description', 'active'] },
  { key: 'contractTerms', title: 'Contract Terms', category: 'Commercial', description: 'Standard terms reusable in supplier purchase contracts.', permission: 'master.manage', fields: [
    { key: 'code', label: 'Code', required: true }, { key: 'name', label: 'Term Name', required: true }, { key: 'text', label: 'Standard Terms Text', type: 'textarea', required: true }, { key: 'active', label: 'Active', type: 'checkbox' }
  ], seed: [{ id: 'CTERM-001', code: 'FFB-BASE', name: 'FFB Base Purchase Terms', text: 'Supplier shall deliver agreed material within the contract period. Quality, weighing and acceptance remain subject to mill procedures.', active: true }, { id: 'CTERM-002', code: 'PAY-OER', name: 'OER-linked Payment Terms', text: 'Payment is calculated using the agreed OER percentage and approved quality basis.', active: true }], columns: ['code', 'name', 'text', 'active'] },
  { key: 'transporters', title: 'Transporters', category: 'Logistics', description: 'Transport companies kept separate from vehicle identity.', permission: 'master.manage', fields: [
    { key: 'code', label: 'Code', required: true }, { key: 'name', label: 'Name', required: true }, { key: 'contact', label: 'Contact' }, { key: 'phone', label: 'Phone' }, { key: 'active', label: 'Active', type: 'checkbox' }
  ], seed: [], columns: ['code', 'name', 'contact', 'phone', 'active'] },
  { key: 'vehicleTypes', title: 'Vehicle Types', category: 'Logistics', description: 'Controlled vehicle classifications used by Vehicle Master and weighbridge transactions.', permission: 'master.manage', fields: [
    { key: 'code', label: 'Code', required: true }, { key: 'name', label: 'Vehicle Type', required: true }, { key: 'usage', label: 'Primary Usage', type: 'select', options: ['FFB Inbound', 'Bulk Liquid', 'Kernel / Dry Cargo', 'General Cargo', 'Internal Transport'], required: true }, { key: 'defaultCapacity', label: 'Default Capacity', type: 'number' }, { key: 'capacityUom', label: 'Capacity UOM', type: 'select', options: ['MT', 'KG'], required: true }, { key: 'requiresTare', label: 'Requires Tare Weighing', type: 'checkbox' }, { key: 'active', label: 'Active', type: 'checkbox' }
  ], seed: [{ id: 'VTYPE-001', code: 'FFB-TIPPER', name: 'FFB Tipper', usage: 'FFB Inbound', defaultCapacity: 25, capacityUom: 'MT', requiresTare: true, active: true }, { id: 'VTYPE-002', code: 'LORRY', name: 'Lorry', usage: 'General Cargo', defaultCapacity: 15, capacityUom: 'MT', requiresTare: true, active: true }, { id: 'VTYPE-003', code: 'TANKER', name: 'CPO Tanker', usage: 'Bulk Liquid', defaultCapacity: 35, capacityUom: 'MT', requiresTare: true, active: true }], columns: ['code', 'name', 'usage', 'defaultCapacity', 'capacityUom', 'active'] },
  { key: 'vehicles', title: 'Vehicles', category: 'Logistics', description: 'Vehicles prepared for future weighbridge usage.', permission: 'master.manage', fields: [
    { key: 'registrationNo', label: 'Registration number', required: true }, { key: 'transporter', label: 'Transporter' }, { key: 'vehicleType', label: 'Vehicle type' }, { key: 'declaredCapacity', label: 'Declared capacity', type: 'number' }, { key: 'capacityUom', label: 'Capacity UOM' }, { key: 'active', label: 'Active', type: 'checkbox' }
  ], seed: [{ id: 'VEH-001', registrationNo: 'JQK 4812', transporter: 'Unassigned', vehicleType: 'FFB tipper', declaredCapacity: 25, capacityUom: 't', active: true }], columns: ['registrationNo', 'transporter', 'vehicleType', 'declaredCapacity', 'active'] },
  { key: 'storageLocations', title: 'Storage Locations', category: 'Storage', description: 'Mill-scoped locations for tanks, silos, yards and storage areas.', permission: 'storage.manage', fields: [
    { key: 'code', label: 'Code', required: true }, { key: 'name', label: 'Name', required: true }, { key: 'mill', label: 'Mill', required: true }, { key: 'kind', label: 'Location type', type: 'select', options: ['Tank', 'Silo', 'Bunker', 'Warehouse Area', 'Ramp', 'Yard'], required: true }, { key: 'active', label: 'Active', type: 'checkbox' }
  ], seed: [{ id: 'LOC-001', code: 'CPO-TANK-01', name: 'CPO Tank 01', mill: 'Main Mill', kind: 'Tank', active: true }, { id: 'LOC-002', code: 'KERNEL-SILO', name: 'Kernel Silo', mill: 'Main Mill', kind: 'Silo', active: true }], columns: ['code', 'name', 'mill', 'kind', 'active'] },
  { key: 'tanks', title: 'Tank Master', category: 'Storage', description: 'Mill-scoped tank capacity and material compatibility configuration.', permission: 'storage.manage', fields: [
    { key: 'code', label: 'Code', required: true }, { key: 'name', label: 'Name', required: true }, { key: 'mill', label: 'Mill', required: true }, { key: 'storageLocation', label: 'Storage location', required: true }, { key: 'compatibleMaterial', label: 'Compatible material' }, { key: 'capacity', label: 'Nominal capacity', type: 'number', required: true }, { key: 'capacityUom', label: 'Capacity UOM', required: true }, { key: 'active', label: 'Active', type: 'checkbox' }
  ], seed: [
    { id: 'TANK-001', code: 'CPO-TANK-01', name: 'CPO Tank 01', mill: 'Main Mill', storageLocation: 'CPO Tank 01', compatibleMaterial: 'CPO', capacity: 600, capacityUom: 't', active: true },
    { id: 'TANK-002', code: 'CPO-TANK-02', name: 'CPO Tank 02', mill: 'Main Mill', storageLocation: 'CPO Tank 02', compatibleMaterial: 'CPO', capacity: 800, capacityUom: 't', active: true },
    { id: 'TANK-003', code: 'CPO-TANK-03', name: 'CPO Tank 03', mill: 'Main Mill', storageLocation: 'CPO Tank 03', compatibleMaterial: 'CPO', capacity: 800, capacityUom: 't', active: true },
    { id: 'TANK-004', code: 'CPO-TANK-04', name: 'CPO Tank 04', mill: 'Main Mill', storageLocation: 'CPO Tank 04', compatibleMaterial: 'CPO', capacity: 1000, capacityUom: 't', active: true },
    { id: 'TANK-005', code: 'PK-TANK-01', name: 'Palm Kernel Tank 01', mill: 'Main Mill', storageLocation: 'Palm Kernel Tank 01', compatibleMaterial: 'PK', capacity: 450, capacityUom: 't', active: true },
    { id: 'TANK-006', code: 'CPO-TANK-05', name: 'CPO Tank 05', mill: 'Main Mill', storageLocation: 'CPO Tank 05', compatibleMaterial: 'CPO', capacity: 1200, capacityUom: 't', active: true },
  ], columns: ['code', 'name', 'mill', 'compatibleMaterial', 'capacity', 'active'] },
  { key: 'productionLines', title: 'Production Lines', category: 'Production', description: 'Mill-scoped production line configuration.', permission: 'production.manage', fields: [
    { key: 'code', label: 'Code', required: true }, { key: 'name', label: 'Name', required: true }, { key: 'mill', label: 'Mill', required: true }, { key: 'capacityPerShift', label: 'Capacity per shift', type: 'number' }, { key: 'capacityUom', label: 'Capacity UOM' }, { key: 'active', label: 'Active', type: 'checkbox' }
  ], seed: [{ id: 'LINE-001', code: 'LINE-01', name: 'Production Line 01', mill: 'Main Mill', capacityPerShift: 240, capacityUom: 't', active: true }], columns: ['code', 'name', 'mill', 'capacityPerShift', 'active'] },
  { key: 'processDefinitions', title: 'Process Definitions', category: 'Production', description: 'Versioned process definitions kept separate from execution.', permission: 'production.manage', fields: [
    { key: 'code', label: 'Code', required: true }, { key: 'name', label: 'Name', required: true }, { key: 'version', label: 'Version', type: 'number', required: true }, { key: 'description', label: 'Description', type: 'textarea' }, { key: 'active', label: 'Active', type: 'checkbox' }
  ], seed: [{ id: 'PROC-001', code: 'OIL-LINE', name: 'Palm Oil Line', version: 1, description: 'SOH flowchart-aligned oil and by-product route.', active: true }], columns: ['code', 'name', 'version', 'active'] },
  { key: 'qualityParameters', title: 'Quality Parameters', category: 'Quality', description: 'Parameter definitions without invented acceptance limits.', permission: 'quality.manage', fields: [
    { key: 'code', label: 'Code', required: true }, { key: 'name', label: 'Name', required: true }, { key: 'dataType', label: 'Data type', type: 'select', options: ['Decimal', 'Integer', 'Text', 'Boolean'], required: true }, { key: 'uom', label: 'UOM' }, { key: 'precision', label: 'Decimal precision', type: 'number' }, { key: 'active', label: 'Active', type: 'checkbox' }
  ], seed: [], columns: ['code', 'name', 'dataType', 'uom', 'active'] },
  { key: 'samplingPlans', title: 'Sampling Plans', category: 'Quality', description: 'Effective-dated sampling schedules, including configurable intervals.', permission: 'quality.manage', fields: [
    { key: 'code', label: 'Code', required: true }, { key: 'name', label: 'Name', required: true }, { key: 'processPoint', label: 'Process point', required: true }, { key: 'material', label: 'Material' }, { key: 'frequencyMinutes', label: 'Interval in minutes', type: 'number', required: true }, { key: 'responsibleRole', label: 'Responsible role' }, { key: 'active', label: 'Active', type: 'checkbox' }
  ], seed: [{ id: 'SPLAN-001', code: 'OIL-BIHOURLY', name: 'Oil monitoring interval', processPoint: 'Pure Oil Tank', material: 'CPO', frequencyMinutes: 120, responsibleRole: 'Quality Inspector', active: true }], columns: ['code', 'name', 'processPoint', 'material', 'frequencyMinutes', 'active'] },
  { key: 'gradingParameters', title: 'Grading Parameters', category: 'Quality', description: 'Configurable FFB grading parameter definitions.', permission: 'quality.manage', fields: [
    { key: 'code', label: 'Code', required: true }, { key: 'name', label: 'Name', required: true }, { key: 'dataType', label: 'Data type', type: 'select', options: ['Decimal', 'Integer', 'Text', 'Boolean'], required: true }, { key: 'uom', label: 'UOM' }, { key: 'active', label: 'Active', type: 'checkbox' }
  ], seed: [], columns: ['code', 'name', 'dataType', 'uom', 'active'] },
  { key: 'gradingRules', title: 'Grading Rules', category: 'Quality', description: 'Versioned grading rule sets; thresholds remain business-configured.', permission: 'quality.manage', fields: [
    { key: 'code', label: 'Code', required: true }, { key: 'name', label: 'Name', required: true }, { key: 'version', label: 'Version', type: 'number', required: true }, { key: 'effectiveFrom', label: 'Effective from', type: 'date' }, { key: 'effectiveTo', label: 'Effective to', type: 'date' }, { key: 'active', label: 'Active', type: 'checkbox' }
  ], seed: [], columns: ['code', 'name', 'version', 'effectiveFrom', 'active'] },
  { key: 'rejectionReasons', title: 'Rejection Reasons', category: 'Quality', description: 'Controlled reasons for rejected or partially rejected material.', permission: 'quality.manage', fields: [
    { key: 'code', label: 'Code', required: true }, { key: 'name', label: 'Reason', required: true }, { key: 'description', label: 'Description', type: 'textarea', required: true }, { key: 'active', label: 'Active', type: 'checkbox' }
  ], seed: [], columns: ['code', 'name', 'description', 'active'] },
  { key: 'numberingSequences', title: 'Numbering Sequences', category: 'System', description: 'Scoped, concurrency-safe business-number configuration.', permission: 'configuration.manage', fields: [
    { key: 'code', label: 'Sequence code', required: true }, { key: 'documentType', label: 'Document type', required: true }, { key: 'prefix', label: 'Prefix', required: true }, { key: 'padding', label: 'Padding', type: 'number', required: true }, { key: 'periodBehavior', label: 'Period behavior', type: 'select', options: ['Never reset', 'Calendar year', 'Calendar month'], required: true }, { key: 'scope', label: 'Scope', type: 'select', options: ['Tenant', 'Company', 'Mill'], required: true }, { key: 'active', label: 'Active', type: 'checkbox' }
  ], seed: [{ id: 'SEQ-001', code: 'FFB_RECEIPT', documentType: 'FFB Receipt', prefix: 'FFB-', padding: 6, periodBehavior: 'Calendar year', scope: 'Mill', active: true }], columns: ['code', 'documentType', 'prefix', 'padding', 'scope', 'active'] }
];

export function getMasterDefinition(key) {
  return masterDefinitions.find((definition) => definition.key === key);
}

export function initialMasterStore() {
  return Object.fromEntries(masterDefinitions.map((definition) => [definition.key, definition.seed.map((record) => ({ ...record }))]));
}
