import React, { useEffect, useMemo, useRef, useState } from "react";
import "./rich-text-editor.css";

const fallbackTerms = [{ code: "FFB-BASE", name: "FFB Base Purchase Terms", text: "Supplier shall deliver agreed material within the contract period. Quality, weighing and acceptance remain subject to mill procedures." }, { code: "PAY-OER", name: "OER-linked Payment Terms", text: "Payment is calculated using the agreed OER percentage and approved quality basis." }];
function masterTerms() { try { const values = JSON.parse(localStorage.getItem("rockeye.master.contractTerms") || "[]"); return values.filter((term) => term.active !== false && term.code && term.text).length ? values.filter((term) => term.active !== false && term.code && term.text) : fallbackTerms; } catch { return fallbackTerms; } }
export function RichTextEditor({ value, onChange, label = "Terms & Conditions", placeholder = "Enter terms and conditions..." }) {
  const ref = useRef(null); const [focused, setFocused] = useState(false); const terms = useMemo(masterTerms, []);
  useEffect(() => { if (ref.current && ref.current.innerHTML !== (value || "")) ref.current.innerHTML = value || ""; }, [value]);
  const command = (name, arg) => { ref.current?.focus(); document.execCommand(name, false, arg); onChange?.(ref.current.innerHTML); };
  const update = () => onChange?.(ref.current?.innerHTML || "");
  return <div className="rich-editor-field"><div className="rich-editor-heading"><strong>{label}</strong><span>Rich text formatting supported</span></div><div className={`rich-editor ${focused ? "focused" : ""}`}><div className="rich-toolbar"><button type="button" onClick={() => command("undo")} title="Undo">↶</button><button type="button" onClick={() => command("redo")} title="Redo">↷</button><select defaultValue="" onChange={(e) => { if (e.target.value) command("formatBlock", e.target.value); e.target.value = ""; }}><option value="">Format</option><option value="p">Paragraph</option><option value="h3">Heading</option><option value="blockquote">Quote</option></select><i /><button type="button" onClick={() => command("bold")}>B</button><button type="button" onClick={() => command("italic")}><em>I</em></button><button type="button" onClick={() => command("underline")}><u>U</u></button><button type="button" onClick={() => command("strikeThrough")}>S</button><i /><button type="button" onClick={() => command("insertUnorderedList")}>☷</button><button type="button" onClick={() => command("insertOrderedList")}>☷</button><button type="button" onClick={() => command("formatBlock", "blockquote")}>❞</button><i /><button type="button" onClick={() => command("justifyLeft")}>≡</button><button type="button" onClick={() => command("justifyCenter")}>≡</button><button type="button" onClick={() => command("justifyRight")}>≡</button><button type="button" onClick={() => command("createLink", window.prompt("Link URL") || "")}>↗</button><button type="button" onClick={() => command("removeFormat")}>Tˣ</button><span className="rich-toolbar-spacer" /><select defaultValue="" onChange={(e) => { const term = terms.find((item) => item.code === e.target.value); if (term) { ref.current.innerHTML = `<p>${term.text}</p>`; onChange?.(ref.current.innerHTML); } e.target.value = ""; }}><option value="">▧ Insert Standard T&C</option>{terms.map((term) => <option key={term.code} value={term.code}>{term.name}</option>)}</select></div><div ref={ref} className="rich-editor-canvas" contentEditable suppressContentEditableWarning data-placeholder={placeholder} onFocus={() => setFocused(true)} onBlur={() => setFocused(false)} onInput={update} /></div><div className="rich-editor-footer"><span><b>●</b> Rich Text Editor Ready</span><span>{(ref.current?.innerText || "").trim().split(/\s+/).filter(Boolean).length} words&nbsp;&nbsp; • &nbsp;&nbsp;{(ref.current?.innerText || "").length} chars</span></div></div>;
}
