import React, { useMemo, useState } from "react";
import "./dispatch.css";

const stages = ["ORDERED", "EMPTY_WEIGHED", "BAY_ASSIGNED", "LOADING", "QUALITY_PENDING", "QUALITY_RELEASED", "LOADED_WEIGHED", "COMPLETED"];
const label = (value) => String(value || "").replaceAll("_", " ");

export function DispatchPage({ rows = [], items = [], onSaved }) {
  const [search, setSearch] = useState("");
  const [selected, setSelected] = useState(null);
  const [modal, setModal] = useState(null);
  const [error, setError] = useState("");
  const products = items.filter((item) => item.status === "Active" && ["CPO", "Palm Kernel", "EFB"].some((name) => item.name.includes(name))).map((item) => item.item_type === "PK" ? "Palm Kernel" : item.item_type || item.name.includes("Palm Kernel") ? "Palm Kernel" : item.name.includes("EFB") ? "EFB" : "CPO");
  const materials = [...new Set(["CPO", "Palm Kernel", "EFB", ...products])];
  const filtered = useMemo(() => rows.filter((row) => `${row.order_no} ${row.material} ${row.customer} ${row.vehicle_no} ${row.status}`.toLowerCase().includes(search.toLowerCase())), [rows, search]);
  const refresh = async () => { await onSaved?.(); };
  const openAction = (type, order) => { setError(""); setModal({ type, order }); };
  const submit = async (event) => {
    event.preventDefault(); setError(""); const form = new FormData(event.currentTarget); let url = ""; let body = {};
    if (modal.type === "new") { url = "/api/dispatch-orders"; body = { material: form.get("material"), customer: form.get("customer"), vehicleNo: form.get("vehicleNo"), driverName: form.get("driverName"), quantity: form.get("quantity") }; }
    if (modal.type === "empty") { url = `/api/dispatch-orders/${modal.order.id}/empty-weighing`; body = { emptyWeight: form.get("weight") }; }
    if (modal.type === "bay") { url = `/api/dispatch-orders/${modal.order.id}/loading-bay`; body = { loadingBay: form.get("loadingBay") }; }
    if (modal.type === "loadingStart") url = `/api/dispatch-orders/${modal.order.id}/loading/start`;
    if (modal.type === "loadingComplete") { url = `/api/dispatch-orders/${modal.order.id}/loading/complete`; body = { loadedQuantity: form.get("loadedQuantity") }; }
    if (modal.type === "quality") { url = `/api/dispatch-orders/${modal.order.id}/quality`; body = { testedBy: form.get("testedBy"), status: form.get("status"), remarks: form.get("remarks"), parameters: [{ parameter: form.get("parameter"), result: form.get("result"), uom: form.get("uom") }] }; }
    if (modal.type === "loaded") { url = `/api/dispatch-orders/${modal.order.id}/loaded-weighing`; body = { loadedWeight: form.get("weight") }; }
    if (modal.type === "exit") { url = `/api/dispatch-orders/${modal.order.id}/vehicle-exit`; body = { tareWeight: form.get("tareWeight") }; }
    try { const response = await fetch(url, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.message || "Dispatch action failed."); setSelected(payload); setModal(null); await refresh(); } catch (err) { setError(err.message); }
  };
  const action = (order) => { if (order.status === "ORDERED") return ["empty", "Empty vehicle weighing"]; if (order.status === "EMPTY_WEIGHED") return ["bay", "Direct to loading bay"]; if (order.status === "BAY_ASSIGNED") return ["loadingStart", "Start loading"]; if (order.status === "LOADING") return ["loadingComplete", "Complete loading"]; if (order.status === "QUALITY_PENDING") return ["quality", "Record quality receipt"]; if (order.status === "QUALITY_RELEASED") return ["loaded", "Loaded vehicle weighing"]; if (order.status === "LOADED_WEIGHED") return ["exit", "Calculate tare & vehicle exit"]; return [null, "Completed"]; };
  return <main className="dispatch-page">
    <div className="customer-breadcrumb"><span>Stock</span><b>›</b><strong>Dispatch</strong></div>
    <div className="customer-list-heading"><div><div className="eyebrow">STOCK / OUTBOUND LOGISTICS</div><h1>Dispatch</h1><p>Control the connected outbound flow from dispatch order to vehicle exit.</p></div><button className="btn btn-primary" onClick={() => { setError(""); setModal({ type: "new" }); }}>＋ New Dispatch Order</button></div>
    <div className="dispatch-flow"><span>Dispatch Order</span><b>→</b><span>Empty Weighing</span><b>→</b><span>Loading Bay</span><b>→</b><span>Loading</span><b>→</b><span>Quality Receipt</span><b>→</b><span>Loaded Weighing</span><b>→</b><span>Vehicle Exit</span></div>
    <section className="panel dispatch-panel"><div className="items-toolbar"><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search order, material, customer or vehicle..." /><span>{filtered.length} dispatch orders</span></div><div className="table-wrap"><table><thead><tr><th>Order</th><th>Material</th><th>Customer</th><th>Vehicle</th><th>Quantity</th><th>Status</th><th>Next action</th></tr></thead><tbody>{filtered.map((row) => { const next = action(row); return <tr key={row.id} onClick={() => setSelected(row)} className="clickable-table-row"><td><button className="table-link" onClick={(event) => { event.stopPropagation(); setSelected(row); }}>{row.order_no}</button></td><td>{row.material}</td><td>{row.customer}</td><td>{row.vehicle_no}</td><td>{Number(row.quantity).toFixed(3)} MT</td><td><span className={`dispatch-status ${String(row.status).toLowerCase()}`}>{label(row.status)}</span></td><td><button className="item-edit" disabled={!next[0]} onClick={(event) => { event.stopPropagation(); openAction(next[0], row); }}>{next[1]}</button></td></tr>; })}{!filtered.length && <tr><td colSpan="7" className="items-empty">No dispatch orders found.</td></tr>}</tbody></table></div></section>
    {selected && <DispatchDetails order={selected} onClose={() => setSelected(null)} onAction={openAction} action={action} />}
    {modal && <DispatchModal modal={modal} materials={materials} error={error} onClose={() => setModal(null)} onSubmit={submit} />}
  </main>;
}

function DispatchDetails({ order, onClose, onAction, action }) {
  const next = action(order);
  return <div className="drawer-backdrop" onClick={onClose}><aside className="drawer dispatch-drawer" onClick={(event) => event.stopPropagation()}><div className="drawer-head"><div><div className="eyebrow">DISPATCH ORDER</div><h2>{order.order_no}</h2></div><button className="icon-button" onClick={onClose}>×</button></div><div className="dispatch-status-bar"><span className={`dispatch-status ${String(order.status).toLowerCase()}`}>{label(order.status)}</span><strong>{order.material} · {Number(order.quantity).toFixed(3)} MT</strong></div><div className="dispatch-timeline">{stages.map((stage, index) => <div key={stage} className={stages.indexOf(order.status) >= index ? "complete" : ""}><i>{stages.indexOf(order.status) >= index ? "✓" : index + 1}</i><span>{label(stage)}</span></div>)}</div><div className="traceability-list"><div><span>Customer</span><strong>{order.customer}</strong></div><div><span>Vehicle</span><strong>{order.vehicle_no}</strong></div><div><span>Driver</span><strong>{order.driver_name || "—"}</strong></div><div><span>Loading bay</span><strong>{order.loading_bay || "Pending"}</strong></div><div><span>Empty weight</span><strong>{order.empty_weight ? `${Number(order.empty_weight).toFixed(3)} MT` : "Pending"}</strong></div><div><span>Loaded weight</span><strong>{order.loaded_weight ? `${Number(order.loaded_weight).toFixed(3)} MT` : "Pending"}</strong></div><div><span>Tare captured</span><strong>{order.tare_weight ? `${Number(order.tare_weight).toFixed(3)} MT` : "Pending"}</strong></div><div><span>Net dispatched</span><strong>{order.net_weight ? `${Number(order.net_weight).toFixed(3)} MT` : "Pending"}</strong></div><div><span>Quality receipt</span><strong>{order.qualityReceipt?.receipt_no || "Pending"}</strong></div></div><div className="drawer-action-strip"><strong>Next step</strong><button className="btn btn-primary" disabled={!next[0]} onClick={() => { onClose(); onAction(next[0], order); }}>{next[1]}</button></div></aside></div>;
}

function DispatchModal({ modal, materials, error, onClose, onSubmit }) {
  const title = { new: "Create Dispatch Order", empty: "Empty Vehicle Weighing", bay: "Assign Loading Bay", loadingStart: "Direct Vehicle to Loading Bay", loadingComplete: "Record Loading Operations", quality: "Sampling & Quality Receipt", loaded: "Loaded Vehicle Second Weighing", exit: "Tare Calculation & Vehicle Exit" }[modal.type];
  return <div className="items-modal-backdrop"><form className="dispatch-form" onSubmit={onSubmit}><div className="items-form-heading"><div><span className="eyebrow">STOCK / DISPATCH</span><h2>{title}</h2><p>{modal.order ? `${modal.order.order_no} · ${modal.order.vehicle_no} · ${modal.order.material}` : "Create a controlled outbound dispatch flow."}</p></div><button type="button" className="icon-button" onClick={onClose}>×</button></div>{error && <div className="form-error">{error}</div>}
    {modal.type === "new" && <div className="contract-grid two"><label className="contract-field">Material<em>*</em><select name="material" required>{materials.map((material) => <option key={material}>{material}</option>)}</select></label><label className="contract-field">Quantity (MT)<em>*</em><input name="quantity" type="number" min="0.001" step="0.001" required /></label><label className="contract-field">Customer<em>*</em><input name="customer" required placeholder="Customer / buyer" /></label><label className="contract-field">Vehicle Registration<em>*</em><input name="vehicleNo" required placeholder="e.g. JQK 4812" /></label><label className="contract-field">Driver Name<input name="driverName" /></label></div>}
    {modal.type === "empty" && <div className="dispatch-step-copy"><p>Capture the empty vehicle weight before the vehicle is directed to the loading bay.</p><label className="contract-field">Empty Vehicle Weight (MT)<em>*</em><input name="weight" type="number" min="0.001" step="0.001" required /></label></div>}
    {modal.type === "bay" && <div className="dispatch-step-copy"><p>The empty-weighed vehicle is now authorized for loading-bay assignment.</p><label className="contract-field">Loading Bay<em>*</em><select name="loadingBay" required><option value="">Select configured bay...</option><option>Bay 01 · CPO Loading</option><option>Bay 02 · Kernel Loading</option><option>Bay 03 · General Materials</option></select></label></div>}
    {modal.type === "loadingStart" && <div className="dispatch-step-copy"><p>Confirm that the vehicle has been directed to the assigned loading bay and loading operations can begin.</p></div>}
    {modal.type === "loadingComplete" && <div className="dispatch-step-copy"><p>Record the quantity loaded before sending the vehicle for sampling.</p><label className="contract-field">Loaded Quantity (MT)<em>*</em><input name="loadedQuantity" type="number" min="0.001" step="0.001" required /></label></div>}
    {modal.type === "quality" && <div className="contract-grid two"><label className="contract-field">Quality Parameter<em>*</em><input name="parameter" required placeholder="FFA, Moisture, Dirt, Temperature" /></label><label className="contract-field">Result<em>*</em><input name="result" required /></label><label className="contract-field">UOM<input name="uom" placeholder="%, °C, ppm" /></label><label className="contract-field">Quality Status<em>*</em><select name="status" required><option>PASS</option><option>REVIEW</option><option>OUT_OF_SPEC</option></select></label><label className="contract-field">Tested By<em>*</em><input name="testedBy" defaultValue="Sean Shapiro" required /></label><label className="contract-field form-wide-field">Remarks<textarea name="remarks" rows="3" /></label></div>}
    {modal.type === "loaded" && <div className="dispatch-step-copy"><p>Capture the second loaded vehicle weighing. The dispatch quantity will be reconciled against the weight difference.</p><label className="contract-field">Loaded Vehicle Weight (MT)<em>*</em><input name="weight" type="number" min="0.001" step="0.001" required /></label></div>}
    {modal.type === "exit" && <div className="dispatch-step-copy"><p>The vehicle has passed quality release and loaded weighing. Confirm or correct the tare used to calculate the final dispatched quantity.</p><label className="contract-field">Tare Weight (MT)<em>*</em><input name="tareWeight" type="number" min="0.001" step="0.001" defaultValue={modal.order.empty_weight || ""} required /></label></div>}
    <div className="contract-actions"><button type="button" className="btn btn-secondary" onClick={onClose}>Cancel</button><button className="btn btn-primary">{modal.type === "new" ? "Create Dispatch Order" : "Save & Continue"}</button></div></form></div>;
}
