import React, { useMemo, useState } from "react";

const emptyItem = { itemCode: "", name: "", category: "Raw Material", itemType: "FFB", unit: "MT", stockUnit: "MT", reorderLevel: "", maxStock: "", leadTimeDays: "", location: "", storageCondition: "Covered / Dry", trackingMethod: "Batch / Lot", qualityInspection: true, specification: "", status: "Active" };
const categories = ["Raw Material", "Finished Product", "By-product", "Consumable", "Chemical", "MRO Spare Part", "Packaging", "Fuel & Utility"];
const itemTypes = ["FFB", "CPO", "Palm Kernel", "PKS / Fiber", "EFB", "Chemical", "Lubricant", "Spare Part", "Packaging", "Utility"];
const units = ["MT", "KG", "Litres", "Pieces", "Drums", "Sets"];

export function ItemsPage({ rows, onSaved }) {
  const [search, setSearch] = useState("");
  const [showForm, setShowForm] = useState(false);
  const [editingId, setEditingId] = useState(null);
  const [form, setForm] = useState(emptyItem);
  const [error, setError] = useState("");
  const filtered = useMemo(() => rows.filter((row) => `${row.item_code} ${row.name} ${row.category} ${row.item_type} ${row.location}`.toLowerCase().includes(search.toLowerCase())), [rows, search]);
  const update = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const openNew = () => { setError(""); setEditingId(null); setForm({ ...emptyItem }); setShowForm(true); };
  const edit = (row) => { setEditingId(row.id); setForm({ ...emptyItem, itemCode: row.item_code, name: row.name, category: row.category, itemType: row.item_type || "FFB", unit: row.unit, stockUnit: row.stock_unit || row.unit, reorderLevel: row.reorder_level ?? "", maxStock: row.max_stock ?? "", leadTimeDays: row.lead_time_days ?? "", location: row.location || "", storageCondition: row.storage_condition || "Covered / Dry", trackingMethod: row.tracking_method || "Batch / Lot", qualityInspection: Boolean(row.quality_inspection), specification: row.specification || "", status: row.status }); setError(""); setShowForm(true); };
  const submit = async (event) => { event.preventDefault(); setError(""); const response = await fetch(editingId ? `/api/items/${editingId}` : "/api/items", { method: editingId ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const payload = await response.json(); if (!response.ok) { setError(payload.message || "Unable to save item."); return; } setForm({ ...emptyItem }); setEditingId(null); setShowForm(false); onSaved(); };
  const remove = async (id) => { if (!window.confirm("Remove this item from the item master?")) return; await fetch(`/api/items/${id}`, { method: "DELETE" }); onSaved(); };
  return <main className="items-page">
    <div className="items-breadcrumb"><span>Stock</span><b>›</b><strong>Items</strong></div>
    <div className="items-heading"><div><h1>Item Master</h1><p>Manufacturing master data for Palm Oil Mill raw materials, products, by-products, chemicals and MRO.</p></div><button className="btn btn-primary" onClick={openNew}>＋ Add Item</button></div>
    <div className="items-summary"><div><span>Total Items</span><strong>{rows.length}</strong></div><div><span>Active Items</span><strong>{rows.filter((row) => row.status === "Active").length}</strong></div><div><span>Batch Tracked</span><strong>{rows.filter((row) => row.tracking_method === "Batch / Lot").length}</strong></div><div><span>Quality Inspected</span><strong>{rows.filter((row) => row.quality_inspection).length}</strong></div></div>
    <article className="panel items-panel"><div className="items-toolbar"><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search item code, name, type or location..." /><span>{filtered.length} items</span></div><div className="table-wrap"><table className="items-table"><thead><tr><th>Item Code</th><th>Item Name</th><th>Type</th><th>Category</th><th>UOM</th><th>Traceability</th><th>Quality</th><th>Location</th><th>Status</th><th>Action</th></tr></thead><tbody>{filtered.map((row) => <tr key={row.id}><td><strong>{row.item_code}</strong></td><td className="item-name">{row.name}</td><td>{row.item_type || "—"}</td><td><span className="classification-pill">{row.category}</span></td><td>{row.unit}</td><td>{row.tracking_method || "—"}</td><td>{row.quality_inspection ? <span className="quality-yes">Required</span> : "Not required"}</td><td>{row.location || "—"}</td><td><span className="customer-status">{row.status}</span></td><td><button className="item-edit" onClick={() => edit(row)}>Edit</button><button className="item-delete" onClick={() => remove(row.id)}>Remove</button></td></tr>)}{!filtered.length && <tr><td colSpan="10" className="items-empty">No items found.</td></tr>}</tbody></table></div></article>
    {showForm && <div className="items-modal-backdrop"><form className="items-form items-form-wide" onSubmit={submit}><div className="items-form-heading"><div><span className="eyebrow">STOCK / MANUFACTURING ITEM MASTER</span><h2>{editingId ? "Edit Item" : "Add Item"}</h2><p>{editingId ? "Update controlled Palm Oil Mill item master data." : "Create a controlled material, product, by-product, chemical or MRO item."}</p></div><button type="button" className="icon-button" onClick={() => setShowForm(false)}>×</button></div>{error && <div className="form-error">{error}</div>}
      <div className="item-form-section"><h3>1. Identification & Classification</h3><div className="contract-grid three"><label className="contract-field">Item Code<em>*</em><input required value={form.itemCode} onChange={(e) => update("itemCode", e.target.value)} placeholder="e.g. RM-CPO-001" /></label><label className="contract-field">Item Name<em>*</em><input required value={form.name} onChange={(e) => update("name", e.target.value)} placeholder="e.g. Crude Palm Oil" /></label><label className="contract-field">Item Type<em>*</em><select value={form.itemType} onChange={(e) => update("itemType", e.target.value)}>{itemTypes.map((option) => <option key={option}>{option}</option>)}</select></label><label className="contract-field">Manufacturing Category<em>*</em><select value={form.category} onChange={(e) => update("category", e.target.value)}>{categories.map((option) => <option key={option}>{option}</option>)}</select></label><label className="contract-field">Item Status<select value={form.status} onChange={(e) => update("status", e.target.value)}><option>Active</option><option>Under Review</option><option>Blocked</option><option>Obsolete</option></select></label></div></div>
      <div className="item-form-section"><h3>2. Inventory, Planning & Storage</h3><div className="contract-grid three"><label className="contract-field">Inventory UOM<em>*</em><select value={form.unit} onChange={(e) => update("unit", e.target.value)}>{units.map((option) => <option key={option}>{option}</option>)}</select></label><label className="contract-field">Stock / Issue UOM<em>*</em><select value={form.stockUnit} onChange={(e) => update("stockUnit", e.target.value)}>{units.map((option) => <option key={option}>{option}</option>)}</select></label><label className="contract-field">Default Location<input value={form.location} onChange={(e) => update("location", e.target.value)} placeholder="e.g. CPO Tank 01" /></label><label className="contract-field">Minimum / Reorder Level<input type="number" min="0" step="0.01" value={form.reorderLevel} onChange={(e) => update("reorderLevel", e.target.value)} placeholder="0.00" /></label><label className="contract-field">Maximum Stock Level<input type="number" min="0" step="0.01" value={form.maxStock} onChange={(e) => update("maxStock", e.target.value)} placeholder="0.00" /></label><label className="contract-field">Supplier Lead Time (Days)<input type="number" min="0" step="1" value={form.leadTimeDays} onChange={(e) => update("leadTimeDays", e.target.value)} placeholder="e.g. 7" /></label><label className="contract-field">Storage Condition<select value={form.storageCondition} onChange={(e) => update("storageCondition", e.target.value)}><option>Covered / Dry</option><option>Temperature Controlled</option><option>Tank / Bulk Liquid</option><option>Outdoor / Bunded</option><option>Secure Store</option><option>Hazardous Chemical Store</option></select></label><label className="contract-field">Traceability Method<select value={form.trackingMethod} onChange={(e) => update("trackingMethod", e.target.value)}><option>Batch / Lot</option><option>Serial Number</option><option>Expiry / Lot</option><option>Not Tracked</option></select></label></div></div>
      <div className="item-form-section"><h3>3. Quality & Technical Control</h3><div className="contract-grid two"><label className="contract-field">Quality Specification / Acceptance Criteria<textarea rows="3" value={form.specification} onChange={(e) => update("specification", e.target.value)} placeholder="e.g. CPO FFA max 4.5%, moisture max 0.25%, dirt max 0.02%" /></label><label className="checkbox-card"><input type="checkbox" checked={form.qualityInspection} onChange={(e) => update("qualityInspection", e.target.checked)} /><span><strong>Quality inspection required</strong><small>Require inspection or laboratory release before the item can be used or dispatched.</small></span></label></div></div>
      <div className="contract-actions"><button type="button" className="btn btn-secondary" onClick={() => setShowForm(false)}>Cancel</button><button className="btn btn-primary">{editingId ? "Update Item" : "Save Item"}</button></div>
    </form></div>}
  </main>;
}
